### ISSUE TITLE
 dialogue closes

### ISSUE THREAD

**Issue by koles-doc96** [muak/AiForms.Dialogs#14]
### Description
if use Editor in DialogView, after entering the text, click to hide the keyboard, the dialogue closes
### Steps to Reproduce

1. entering the text to Editor
2. click to hide the keyboard
3. dialog Closes

### Expected Behavior
the dialogue does not close, then we use the form
### Actual Behavior
dialog Closes
### Platforms

- [x] Android
- [ ] iOS

### Basic Information

- AiForms.SettingsView.DialogView
- Xamarin.Forms 4.7.0.848-pre3 
- Android Support Library Version: 1.0.3
- Affected Devices: Pixel 2, Honor 10

### Screenshots

https://prnt.sc/svgcno

**Comment by koles-doc96** [comment]
Very convenient library, how soon can you fix this bug? I would be very grateful to you.

**Comment by RGBPlaza** [comment]
When pressing the back button to close the keyboard on Android, the dialog is dismissed - which will be a great cause of irritation for many users. Please fix this.

**Comment by muak** [comment]
@koles-doc96 @RGBPlaza 

Thank you for your reports.

This issue is fixed.
