### ISSUE TITLE
RunDismissalAnimation is not invoked when dialog is closed with the back button.

### ISSUE THREAD

**Issue by RGBPlaza** [muak/AiForms.Dialogs#16]
### Description
When dialogs are closed using the dialog notifier, there is not a problem, however when using the back button to close a dialog, the RunDismissalAnimation() method override is not being executed.

### Steps to Reproduce

1. Create page that launches a new dialog view
2. Have an override specified for RunDismissalAnimation()
3. Close dialog using back button 

### Expected Behavior
Code in the override method is executed

### Actual Behavior
The method is not run

### Platforms

- [x] Android
- [ ] iOS

### Basic Information

- AiForms.Dialogs 1.0.7
- Xamarin.Forms 4.7.0
- Affected Devices: Nokia 7 Plus

**Comment by angelru** [comment]
the same issue, any solution?? #18

**Comment by angelru** [comment]
@muak

**Comment by muak** [comment]
@RGBPlaza 
Thank you for your report.

I fixed this issue.
Please wait for the next release.
