### ISSUE TITLE
Java.Lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnTouchListener(android.view.View$OnTouchListener)' on a null object reference

### ISSUE THREAD

**Issue by MauroRomer** [muak/AiForms.Dialogs#2]
Hello There.

Thank you for create and share this with us. It is really helpful.

I identified a problem with a specific version of Android @7.1.1. Please find attached more information about the Device (Samsung SM-T350 - Android 7.1 - API 25).
![SAMSUNG@7 1 1](https://user-images.githubusercontent.com/23048361/58267288-f3a05880-7d48-11e9-8a68-ab09603ee6ff.jpg)

**The problem:**  

> Java.Lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnTouchListener(android.view.View$OnTouchListener)' on a null object reference

However, if you put a breakpoint after  ` Toast.Instance.Show<MyToastView>(new { Title = "Hello", Duration = 1500 })`  you will see a different error:
> Android.Views.WindowManagerBadTokenException: Unable to add window -- token android.os.BinderProxy@25b4943 is not valid

**When it happens**: 
After the command` Toast.Instance.Show<MyToastView>(new { Title = "Hello", Duration = 1500 })` to show the Toast. I am calling that command from an async button click event.

**Where it happens:**
I debugged the code and I could see that in the AiForms.Dialogs.Android.ToastImplementation on  `public void Show(ToastView view, object viewModel = null)` at line 113  `toast.View = null;` where the error shows up.

**Workaround:**
I commented the line 113  `toast.View = null;` and the error is gone.

I am not sure if there is a good solution for that or if you can fix it.

I really appreciate if you could take a look.

Thank you so much,
Mauro Romer

**Comment by muak** [comment]
@MauroRomer 
Thank you for your report and workaround.
I will confirm and fix it.
Please wait for some while.

**Comment by muak** [comment]
@MauroRomer 
I couldn't reproduce it, but I let this code disable because it has no influent even if it is disabled.

This fix will include in the next release.
