### ISSUE TITLE
How can I access the viewModel properties from the code behind?

### ISSUE THREAD

**Issue by sqrg** [muak/AiForms.Dialogs#7]
I have this
```
Dialog.Instance.ShowAsync<GradientDialogView>(new { Content = "Sample alert text", OkText = "OK", GradientInitialColor = "#ED213A" });
```

And I would like to access the `Content`, `OkText`, and `GradientInitialColor` in the code behind of the DialogView. Is there a way to do this?

**Comment by nexussays** [comment]
The object you pass in to `ShowAsync()` is set as the `BindingContext` of the dialog view, so just using `Binding` like normal.

**Comment by sqrg** [comment]
It's not working for me (I can access the `BindingContext` in the .xaml but for some reason I'm not able to do it from the code-behind)

I used the DialogView constructor as a work-around, like [this](https://github.com/sqrg/AiFormsDialogsGradientSample/blob/master/AiFormsDialogSample/Views/Dialogs/GradientDialogView.xaml.cs)

**Comment by nexussays** [comment]
BindingContext isn't going to be set in the constructor. https://github.com/muak/AiForms.Dialogs/blob/master/AiForms.Dialogs.Android/DialogImplementation.cs#L27

**Comment by sqrg** [comment]
Yes, I get it. But how can I access that BindingContext from the code behind?

**Comment by nexussays** [comment]
What is the actual code you are having the problem with? Accessing the BindingContext property should just work.

**Comment by muak** [comment]
@sqrg 
First of all, the BindingContext can be get in OnBindingContextChanged override method. 
The type of BindingContext  is object type.
So you should cast to an appropriate type.
Because of using an anonymous class in your sample,  you should use the defined class.

```cs
public class Some
{
   public string Content {get;set;}
   public string OkText {get;set;}
   public string GradientInitialColor {get;set;}
}
```

```cs
Dialog.Instance.ShowAsync<GradientDialogView>(new Some { Content = "Sample alert text", OkText = "OK", GradientInitialColor = "#ED213A" });
```

```cs
protected override void OnBindingContextChanged()
{
    base.OnBindingContextChanged();
    if(BindingContext is Some some)
    {
        Content  = some.Content;
        ... omit
    }
}
```

However, It seems that data binding is usually used when like this pattern.

**Comment by muak** [comment]
@nexussays 
Thank you for your answer!

**Comment by nexussays** [comment]
@muak Thank you for sharing the lib!

**Comment by sqrg** [comment]
Thank you both for your answers! But I'm afraid it is not working for me. I'm sure I'm the one doing something wrong, but I can't figure it out.

[Here's the sample with the issue](https://github.com/sqrg/AiFormsDialogsGradientSample/tree/binding-issue)

**Comment by sqrg** [comment]
See https://github.com/sqrg/AiFormsDialogsGradientSample/blob/binding-issue/AiFormsDialogSample/MainPage.xaml.cs#L23

And https://github.com/sqrg/AiFormsDialogsGradientSample/blob/binding-issue/AiFormsDialogSample/Views/Dialogs/GradientDialogView.xaml.cs#L21

**Comment by muak** [comment]
@sqrg 
The parameters of the dialogview constructor are unnecessary.

**Comment by sqrg** [comment]
Ohhhh I'm so stupid

Thanks
